---
title: "Data Structures and Operations - week 2"
author: "Mário O. de Menezes"
date: "07/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/datasets/Neurohacking_data-0.2/BRAINIX/")
```

```{r}
library(oro.dicom)
```
```{r}
setwd("~/datasets/Neurohacking_data-0.2/BRAINIX/DICOM/FLAIR")
```
# DICOM Files

## Loading one slice of DICOM image set

```{r}
slice <- readDICOM("DICOM/FLAIR/IM-0001-0011.dcm")
```
```{r}
class(slice)
```
```{r}
names(slice)
```
```{r}
class(slice$hdr)
```
```{r}
class(slice$hdr[[1]])
```
```{r}
class(slice$img)
```
```{r}
class(slice$img[[1]])
```
```{r}
dim(slice$img[[1]])
```
```{r out.width='4cm', out.height='4cm'}
d <- dim(t(slice$img[[1]]))
image(1:d[1], 1:d[2], t(slice$img[[1]]), col = gray(0:64/64))
```

```{r}
slice$img[[1]][101:105,121:125]
```

```{r}
hist(slice$img[[1]][,],breaks = 50, xlab = "FLAIR", prob=T, col=rgb(0,0,1,1/4), main = "")
```

## DICOM Header Information

```{r}
hdr <- slice$hdr[[1]]
names(hdr)
```


```{r}
hdr$name
```

```{r}
# resolution of image (in mm)
# dimension of each pixel
hdr[hdr$name == "PixelSpacing", "value"]
```

```{r}
# image acquisition parameter
# put in the experimental method of a paper
hdr[hdr$name == "FlipAngle",]
```

## Loading multiple DICOM Files


```{r}
slice_T1 = readDICOM("DICOM/T1/IM-0001-0007.dcm")
```

```{r}
all_slices_T1 <- readDICOM("DICOM/T1/")
```

```{r}
dim(all_slices_T1$img[[11]])
```
```{r}
hdr <- all_slices_T1$hdr[[11]]
```
```{r}
# higher resolution, smaller pixel dimensions
hdr[hdr$name == "PixelSpacing","value"]
```


# NIfTI Format

## From DICOM to NIfTI

```{r}
nii_T1 <- dicom2nifti(all_slices_T1)
```
```{r}
d <- dim(nii_T1); d; class(nii_T1)
```
```{r}
image(1:d[1], 1:d[2], nii_T1[,,11], col=gray(0:64/64), xlab = "", ylab = "")
```

## Write and Read NIfTI Files


```{r}
library(oro.nifti)
```

```{r}
fname = "Output_3D_File"
writeNIfTI(nii_T1, filename=paste0("NIfTI/",fname))
list.files("NIfTI/", pattern = "Output_3D_File")
```

```{r}
list.files("NIfTI/", pattern = "T")
```

```{r}
nii_T2 <- readNIfTI("NIfTI/T2.nii.gz", reorient = FALSE)
dim(nii_T2)
```


